### ISSUE TITLE
sauceConnectOpts + verbose 

### ISSUE THREAD

**Issue by brianjoyner** [webdriverio/wdio-sauce-service#16]
Using wdio-sauce-service 0.3.0

Looks like sauceConnectOpts + the verbose option is not working with the latest release.  Nothing is being logged out.

```
    protocol: 'http',
    services: ['sauce'],
    user:   process.env.sauceuser,
    key:    process.env.saucepass,
    sauceConnectOpts : {
            tunnelDomains : '*.888888.com',
            tunnelIdentifier : sltunnel,
            verbose: true
    },
    sauceConnect: true,
```

I uninstalled and installed 0.2.5 and the same issue is occurring - nothing is being logged out.

**Comment by christian-bromann** [comment]
> nothing is being logged out.

@brianjoyner have you checked the SC log file? WebdriverIO doesn't get these logs. You can specify a custom path for you log file using the `logfile` config.
