### ISSUE TITLE
Allow connecting to an existing Sauce-Connect 

### ISSUE THREAD

**Issue by si-mikey** [webdriverio/wdio-sauce-service#18]
Is it possible to launch this service to connect to an existing sauce-connect tunnel that is already set up in saucelabs? This service seems to launch one automatically.

**Comment by christian-bromann** [comment]
yes, just set host and port to the started SC server and don't start one with the service

**Comment by si-mikey** [comment]
Great!, would be it be something like ? much appreciated.

```
sauceConnectOpts : {
  host: maki0000.miso.saucelabs.com
}
```

**Comment by christian-bromann** [comment]
no. If you have SC already running on port 4445, just set host to localhost and port to 4445 in your wdio.config

**Comment by stsvilik** [comment]
I had same scenario where SC was already running locally, so all I needed to do is to specify ```tunnelIndicator``` inside a capability descriptor. I didn't touch host or port.
