### ISSUE TITLE
Sauce/Appium example

### ISSUE THREAD

**Issue by stsvilik** [webdriverio/wdio-sauce-service#19]
I know there is wdio-appium, but I could not find any example of using SauceLabs Appium capabilities. Is there a way to provide an example of mobile testing through SauceLabs and Appium together?

**Comment by christian-bromann** [comment]
@stsvilik have you seen https://github.com/webdriverio/webdriverio/tree/master/examples/appium? It is not using sauce labs but you only need to add user and key to the config options and you get it.

**Comment by stsvilik** [comment]
@christian-bromann example you provided is for stand-alone test where I'm using wdio runner through gulp-wdio. I guess thats what makes it confusing. Ideally I'm looking for a recipe where wdio is used with sauce labs and appium, and where say two parallel tests run for Android and iOS.

**Comment by christian-bromann** [comment]
I don't have that example on hand but you just copy the desired capabilities into your wdio config and use all commands in a sync way.

**Comment by stsvilik** [comment]
As for "services" param, would I still use "sauce" or "appium"?

**Comment by christian-bromann** [comment]
only the sauce service is necessary
