### ISSUE TITLE
Running sauce service through SauceConnect Proxy throws errors

### ISSUE THREAD

**Issue by brownad** [webdriverio/wdio-sauce-service#21]
If I use this service it throws errors on completion of each test:

Error: connect ETIMEDOUT 1xx.2xx.75.243:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

Removing `sauce` service and tests run quickly without errors.  I am using `http` protocol inside my wdio.config.js but forced on to `https` - undesirable.  I think there's a problem with this service under those conditions

**Comment by christian-bromann** [comment]
Please also set port to 80 as well.
duplicate webdriverio/webdriverio#1911

**Comment by brownad** [comment]
Where for the SauceConnect port you mean? Instead of 4445, then open that up too?

**Comment by christian-bromann** [comment]
Port 80 is wrong, sorry. Please set host (localhost) and port (4445) in your config as well as protocol (http) to `http`.

**Comment by brownad** [comment]
I have set host, port and protocol.  With this plugin it is throwing errors back:

host: sauceconnect.dns
port: 4445
protocol: http

Tests run as https on saucelabs as you mentioned, then throws the error at the end of each test:

**Comment by christian-bromann** [comment]
Do you have any Sauce Connect logs?
