### ISSUE TITLE
When I enable the sauce service in my test suite, it sets the suite name and not the test case name

### ISSUE THREAD

**Issue by deeptiagrawa** [webdriverio/wdio-sauce-service#25]
I added the following lines in my wdio.config.js file to enable the sauce service:

```
   services: ['sauce'],
   user: <username>,
   key: <access_key>
```

When I run the tests on sauce, while the test is executing, the test case name is not set. Once the job is complete, the test case name gets set to the suite name in the sauce and not the full title of the test case.

**Comment by christian-bromann** [comment]
@deeptiagrawa this is exactly what it suppose to do. WebdriverIO runs one spec in one session so it only makes sense to set the suite name of that spec as job name.
