### ISSUE TITLE
Feature Request: ability to specify SauceLabs build

### ISSUE THREAD

**Issue by ericmacfarland** [webdriverio/wdio-sauce-service#33]
I think this is the same as issue #30, but with more detail.

SauceLabs supports annotating tests with [build numbers](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-BuildNumbers), which allows tests to be grouped together into a "build".

Can this functionality be added to the `wdio-sauce-service`?

**Comment by christian-bromann** [comment]
Yes, just have a [`build`](https://github.com/webdriverio/webdriverio/blob/master/test/conf/travis-ci.js#L21) capability set.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by ericmacfarland** [comment]
My mistake, I opened this issue before fully vetting it out

**Comment by christian-bromann** [comment]
No problem 😉
