### ISSUE TITLE
v0.4.6 released via npm, but not part of repo 

### ISSUE THREAD

**Issue by fstoerkle** [webdriverio/wdio-sauce-service#43]
Hi,

our greenkeeper bot notified us about an update to `wdio-sauce-service` to version `0.4.6.` which [npm displays as the latest one released](https://www.npmjs.com/package/wdio-sauce-service).

However, I can't find version 0.4.6 neither in the commit history or in the tags of the repo.

Maybe the new version was never pushed to GitHub?

Would be great to update this repo so that we can see what changes the new version introduces.

Thanks!

**Comment by christian-bromann** [comment]
@fstoerkle thanks for pointing this out. I think I might run into issues while releasing the package and did another release without pushing it to master. Just did tho.

**Comment by fstoerkle** [comment]
Sweet, thanks!
