### ISSUE TITLE
Reporting capability at testcase level 

### ISSUE THREAD

**Issue by kmnaid** [webdriverio/wdio-sauce-service#48]
In the reporting on SauceLabs we see test suites but we are not able to see individual test cases.
If we have the below two suites, in the report you see suite and suite 2 appearing, but we would like to have 'suite1 testcase 1', 'suite1 testcase 2', 'suite2 testcase 1', 'suite2 testcase 2' appear.

Testsuite1.js

 ```
describe('Suite 1') {
 it('suite1 testcase 1'){
   //verify something
 }
 it('suite1 testcase 2'){
   //verify something
 }
}
```
 
Testsuite2.js

```
describe('Suite 2') {
 it('suite2 testcase 1'){
   //verify something
 }
 it('suite2 testcase 2'){
   //verify something
 }
}

```
![image](https://user-images.githubusercontent.com/19783089/37621602-c0e75908-2b95-11e8-8459-7b14193a72da.png)

**Comment by christian-bromann** [comment]
@kmnaid this is not possible. WebdriverIO is creating a session for each individual file and takes the name of the outer describe block as name of the test. If you have further questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
