### ISSUE TITLE
Sends failures to sauce on passing tests with Jasmine

### ISSUE THREAD

**Issue by markbrouch** [webdriverio/wdio-sauce-service#49]
I believe this service sends failures to Saucelabs when tests are passing when using Jasmine (`wdio-jasmine-framework@^0.3.2`).

I console logged the `afterTest` hook like so:
```js
function afterTest(test) {
            if (!test.passed) {
                console.log('==========afterTest didn\'t pass==========')
                console.log(test)
                ++this.failures;
            }
        }
```

and the result of a passing test in my console looks like:
```
==========afterTest didn't pass==========
{ type: 'afterTest',
  title: 'should have title',
  fullName: 'track track response context page should have title',
  file: '/Users/markbrouch/Sites/doximity/dox-analytics/packages/js/test/specs/track.spec.js',
  duration: 125 }
```

In other words, I don't believe Jasmine includes `passed` on the `test` object sent to the `afterTest` hook, causing this service to incorrectly report failures on passing tests.

**Comment by markbrouch** [comment]
I believe this issue is causing the problem: https://github.com/webdriverio/wdio-jasmine-framework/issues/97

**Comment by christian-bromann** [comment]
@markbrouch you right, let's continue discussing this in webdriverio/wdio-jasmine-framework#97
