### ISSUE TITLE
Timeout errors when multiple jobs run concurrently on saucelabs

### ISSUE THREAD

**Issue by kurtharriger** [webdriverio/wdio-sauce-service#5]
We created a CI job that verifies every pull request.   We have a saucelabs concurrency limit of 10 and maxInstances in our wdio.conf.js is also set to 10.  This seems to work fine provided that only one CI job is running at a time, but if multiple CI jobs are run concurrently they almost always fail.  

My guess is that the test is starting before a saucelabs vm is available so our test will timeout while waiting for a VM to become available?  Is it possible to prevent starting a test runner or perhaps temporarily increase the timeout until VM is available and then reset the timeout to configured value?

**Comment by christian-bromann** [comment]
> our test will timeout while waiting for a VM to become available?

Yes, that is the case

> temporarily increase the timeout until VM is available and then reset the timeout to configured value?

I think we could something like this. We could use the onPrepare hook to check the users concurrency value and see how many available instances there are. The problem I see is let's they that there is one capability available because a different build has finished a test but hasn't finished. Should the service then kick off the test? When do we know that we can kick off the build?

**Comment by kurtharriger** [comment]
I don't suppose there might be a way for the sauce service to somehow reserve the VM before starting the test and then use that vm for the test runner.  Thus test would only start after the vm has been reserved.

**Comment by kurtharriger** [comment]
> The problem I see is let's they that there is one capability available because a different build has finished a test but hasn't finished. 

Not ideal, but we could probably set maxInstances to 9 thus if such a race condition occurs both will succeeded.  That would be better than limiting the concurrency on our CI jobs and dedicating a few instances to each.

**Comment by christian-bromann** [comment]
@kurtharriger well the service doesn't know about other builds that are going on. The only thing it can find out is how many instances are available but that doesn't help much. Also we can only check that in the onPrepare hook. To do stuff in the before hook we have to establish a session which won't work if all vms are blocked.

Maybe we could check if there is a build running at that moment. But I am not sure how much that really helps because that build might be triggered by a different project.

**Comment by kurtharriger** [comment]
My understanding of how this all works is still very limited so I probably need to spend more time looking at the code.. but I don't think it needs to know what other builds are going on.

My thinking is that the vm session should be established before the test is established. I'm assuming  onPrepare is not subject to the jasmine timeout interval and thus it would block here until the vm is actually acquired rather than 1 instance is available. Then once acquired it would run the test using this session.  

I'm not actually sure where all this currently happens, in a quick look of the code it looks like onPrepare sets up the tunnel, but I'm not really sure how or where VMs are allocated.  Maybe oPrepare is driver hook that just does the tunnel for all tests and before is the per spec code that allocates the vm which would make it more complicated.  But if prepare runs for each runner then maybe this is feasible?

**Comment by christian-bromann** [comment]
> I'm assuming onPrepare is not subject to the jasmine timeout interval and thus it would block here until the vm is actually acquired

Kinda, onPrepare can hold off the actual execution of the test. However once you kick it off it will start spawning all vms that are required based on spec file and capability number. So even if we wait until one vm is available it could start to ask for way more than just one vm.

> I'm not actually sure where all this currently happens

As I said onPrepare gets executed before the launcher spawns all sub processes.

> how or where VMs are allocated

A vm gets allocated if you ask for a session (between onPrepare and before hook).

> before is the per spec code that allocates the vm

The before hook gets executed once a vm got allocated.

**Comment by kurtharriger** [comment]
Okay, so if I understand correctly onPrepare is a hook is run in the cli launcher process to set up the sauce tunnel and is not subject to the jasmine timeout, but runs only once for all test suites.   The before hook actually starts the VM, but is run in the child runner process and is subject to the jasmine timeout interval.  
I think it would be okay to spawn the runner process and have the runner process block until a vm is available, but the before hook doesn't sound like it can do this.  Perhaps the runner process needs an additional hook that is invoked before starting jasmine which could setup the saucelabs instance prior to starting jasmine runner?

**Comment by christian-bromann** [comment]
> to set up the sauce tunnel and is not subject to the jasmine timeout, but runs only once for all test suites

Yes

> The before hook actually starts the VM

No the wdio runner starts the vm

> but is run in the child runner process

Yes

> and is subject to the jasmine timeout interval

No, the before hook is getting executed before jasmine starts

I believe an additional hook that gets executed before a new vm gets allocated might do the trick but I am not really a fan of adding another hook for that which only would fulfill that purpose. I believe it is a better idea to check if a build is already running and only kick off new builds when no build is running.

**Comment by christian-bromann** [comment]
> I am not really a fan of adding another hook

Stupid me from the past 😆  .. WebdriverIO supports now a beforeSession hook that allows to defer the session initialization until a certain state (available VMs) is met.
