### ISSUE TITLE
Missing commit in release 0.4.11

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/wdio-sauce-service#57]
Hello,

I've noticed that on this repo the latest tag is 0.4.10 however on npm the latest version is 0.4.11

Nevertheless, [the following commit](https://github.com/webdriverio-boneyard/wdio-sauce-service/commit/556208bfc5cf5c58ac3cae3a0c92ed1b2817b0ce) is not included in 0.4.11

Would it be possible to release a new version with that fix please ?

Thanks

**Comment by christian-bromann** [comment]
That commit is included in `v0.4.11` which is released to NPM.

**Comment by Kignuf** [comment]
@christian-bromann sorry but I have to insist as I've inspected the package and the fix isn't there.
Maybe the build went wrong somehow ?
