### ISSUE TITLE
Vulnerability of cryptiles

### ISSUE THREAD

**Issue by yairkukielka** [webdriverio/wdio-sauce-service#58]
`npm audit` fails with the current version of `wdio-sauce-service` (0.4.12)
See advisory here: https://www.npmjs.com/advisories/720

![advisory](https://user-images.githubusercontent.com/11599360/48030579-5fe9a080-e106-11e8-8d70-bbd794e312ba.png)

Please update to the last version of `request` in npm, which has this problem solved, since it relies on version 7 of `hawk`

**Comment by christian-bromann** [comment]
just did
