### ISSUE TITLE
Separate jobs by test case

### ISSUE THREAD

**Issue by danenespoli** [webdriverio/wdio-sauce-service#6]
If there are multiple test cases within a single spec file, it will report the file as a whole. This makes it difficult to determine which tests fail, and also means that it will not run all tests in the file (stopping after the first fail). 

Is there a possible way around this (other than separating test cases into individual files)?

**Comment by christian-bromann** [comment]
No there is not. Each test file will be run in one Selenium session, therefor one Sauce job. There is no plans to change this behavior.

> This makes it difficult to determine which tests fail

Why is that? Your reporter should tell you exactly what happened.

**Comment by danenespoli** [comment]
I only meant it is not obvious which tests failed when looking at the Sauce Labs dashboard alone; unless I'm mistaken you would need to check the command list to see the test annotations containing the name of the test case.

**Comment by christian-bromann** [comment]
Oh I see, yeah I might can try to have longer test names and put more information in it like failed test

**Comment by danenespoli** [comment]
That would be helpful. Even still, that information is buried in the list of GET and POST requests for that Sauce job, isn't it?

**Comment by christian-bromann** [comment]
> That would be helpful. Even still, that information is buried in the list of GET and POST requests for that Sauce job, isn't it?

Not even that. If an assertion fails that will not be recognised by sauce

**Comment by danenespoli** [comment]
Also, on the topic of more detailed reporting, I noticed in mocha the service reports the title based on the outermost `describe`. In my case, that `describe` contains the feature name, which persists across different test files, so two different files could report to sauce with the same name. The innermost `describe` is what is unique to the test file.

Unsure if this would work on other frameworks or other test suites, but it would be beneficial if it reported the name based on `test.parent` instead of `suite.title`, or some concatenation of the two, or at least be given that option to change it.
