### ISSUE TITLE
Option to only use sauce connect

### ISSUE THREAD

**Issue by praihan** [webdriverio/wdio-sauce-service#8]
I'd like to use the connect part only (as we have custom reporting).

I was thinking an additional option in the config, `sauceReport`. `sauce-service.js` would check in `onPrepare` like

``` js
if (typeof config.sauceReport !== 'undefined' && config.sauceReport === false) {
 this.enabled = false;
}
```

A problem might be the fact that `onPrepare` is run on a different process than the rest of them. Thoughts?

**Comment by christian-bromann** [comment]
Why don't you want to update your test name and add context to your tests?

**Comment by praihan** [comment]
We already have our own reporter. And we have to report in that format for compatibility reasons.

**Comment by christian-bromann** [comment]
> We already have our own reporter.

How does that have to do with report?

**Comment by praihan** [comment]
It updates the saucelabs job with custom title and tags.

**Comment by praihan** [comment]
My point really is, this project is doing two things:
1. fire up sauce-connect
2. report test results to saucelabs

We already have our own solution for part 2 (using wdio hooks). So we would like to only use part 1. So _my_ options are to:
1. Roll our own sauce-connect thing.
2. Add the option to opt out of reporting in this project.

I didn't want to start work on a PR if you don't like the idea, or if you have a better solution that could be of help to us.

Cheers and I appreciate your constant efforts to make life with webdriverio easier :+1:

**Comment by christian-bromann** [comment]
> Roll our own sauce-connect thing.

I think this is the best solution. If you already update the job status by yourself, you should either consider to let this be the job of this service or also implement your own SC integration (using a package like https://www.npmjs.com/package/sauce-connect-launcher).
